'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';

type Task = { task_id: string; shoot_id: string; edit_id: string; task_type: string; task_label: string; client_name: string; assigned_to_name: string; assigned_to_email: string; status: string; deadline_at: string };
type Props = { editors: { name: string; email: string }[]; canReallocate: boolean };

export function ManagerTaskBoard({ editors, canReallocate }: Props) {
  const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<Task | null>(null); const [filter, setFilter] = useState('');
  const [editorName, setEditorName] = useState(''); const [reason, setReason] = useState(''); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false);
  const refresh = useCallback(async () => { try { const response = await fetch('/api/editor-tasks', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setTasks(data); } catch (error) { toast.error('Unable to load task board', { description: error instanceof Error ? error.message : undefined }); } finally { setLoading(false); } }, []);
  useEffect(() => { refresh(); }, [refresh]);
  const groups = useMemo(() => { const needle = filter.trim().toLowerCase(); const visible = needle ? tasks.filter((task) => [task.shoot_id, task.edit_id, task.client_name].some((value) => value.toLowerCase().includes(needle))) : tasks; return Array.from(visible.reduce((map, task) => { const key = task.task_type || 'other'; map.set(key, [...(map.get(key) ?? []), task]); return map; }, new Map<string, Task[]>()).entries()); }, [tasks, filter]);
  const begin = (task: Task) => { setSelected(task); setEditorName(''); setReason(''); setNote(''); };
  const confirm = async () => { if (!selected || !editorName || !reason) { toast.error('Choose an editor and reason'); return; } const editor = editors.find((item) => item.name === editorName); if (!editor) return; setSaving(true); try { const response = await fetch('/api/reallocate-task', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ task_id: selected.task_id, new_editor_name: editor.name, new_editor_email: editor.email, reason, manager_note: note }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Failed to reallocate'); toast.success('Task reallocated'); setSelected(null); await refresh(); } catch (error) { toast.error('Could not reallocate task', { description: error instanceof Error ? error.message : undefined }); } finally { setSaving(false); } };
  return <Card className="mb-6"><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">Task Board</CardTitle><Button variant="outline" size="sm" onClick={refresh}>Refresh</Button></CardHeader><CardContent className="space-y-5"><Input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filter by shoot ID, edit ID, or client" />{loading ? <p className="text-sm text-muted-foreground">Loading tasks…</p> : groups.length === 0 ? <p className="py-4 text-center text-sm text-muted-foreground">No individual editing tasks yet.</p> : groups.map(([type, group]) => <div key={type}><h3 className="mb-2 text-sm font-semibold capitalize">{type.replace(/_/g, ' ')} ({group.length})</h3><div className="grid gap-2 md:grid-cols-2">{group.map((task) => <div key={task.task_id} className="rounded-md border border-border p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-medium">{task.task_label || type}</p><p className="text-xs text-muted-foreground">{task.client_name} · {task.assigned_to_name || 'Unassigned'}</p></div><Badge variant="outline">{task.status}</Badge></div><div className="mt-3 flex items-center justify-between gap-2"><p className="text-xs text-muted-foreground">Deadline: {task.deadline_at || '-'}</p>{canReallocate && <Button size="sm" variant="outline" onClick={() => begin(task)}>Reallocate</Button>}</div></div>)}</div></div>)}</CardContent>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>Reallocate Task</DialogTitle><DialogDescription>{selected?.task_label || 'Move this task to another editor.'}</DialogDescription></DialogHeader><div className="space-y-3"><div><Label>Current editor</Label><Input value={selected?.assigned_to_name ?? ''} readOnly className="mt-1 bg-muted" /></div><div><Label>New editor</Label><Select value={editorName} onValueChange={setEditorName}><SelectTrigger className="mt-1"><SelectValue placeholder="Choose editor" /></SelectTrigger><SelectContent>{editors.map((editor) => <SelectItem key={editor.email} value={editor.name}>{editor.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Reason</Label><Select value={reason} onValueChange={setReason}><SelectTrigger className="mt-1"><SelectValue placeholder="Choose reason" /></SelectTrigger><SelectContent>{['On Leave', 'Client Preference', 'Mid-project Switch', 'Other'].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div><Label>Manager note (optional)</Label><Textarea value={note} onChange={(event) => setNote(event.target.value)} className="mt-1" /></div></div><DialogFooter><Button variant="outline" onClick={() => setSelected(null)}>Cancel</Button><Button onClick={confirm} disabled={saving}>Confirm</Button></DialogFooter></DialogContent></Dialog>
  </Card>;
}
